[package]
name = "wit-bindgen-cli"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
homepage = 'https://github.com/bytecodealliance/wit-bindgen'
description = """
CLI tool to generate bindings for WIT documents and the component model.
"""

[workspace]
members = [
  "crates/test-rust-wasm",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.28.0"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
repository = "https://github.com/bytecodealliance/wasi-rs"

[workspace.dependencies]
anyhow = "1.0.75"
bitflags = "2.4.1"
heck =  { version = "0.5" }
pulldown-cmark = { version = "0.9", default-features = false }
clap = { version = "4.3.19", features = ["derive"] }
indexmap = "2.0.0"
prettyplease = "0.2.20"
syn = { version = "2.0", features = ["printing"] }

wasmparser = "0.214.0"
wasm-encoder = "0.214.0"
wasm-metadata = "0.214.0"
wit-parser = "0.214.0"
wit-component = "0.214.0"

wit-bindgen-core = { path = 'crates/core', version = '0.27.0' }
wit-bindgen-c = { path = 'crates/c', version = '0.27.0' }
wit-bindgen-rust = { path = "crates/rust", version = "0.27.0" }
wit-bindgen-teavm-java = { path = 'crates/teavm-java', version = '0.27.0' }
wit-bindgen-go = { path = 'crates/go', version = '0.27.0' }
wit-bindgen-csharp = { path = 'crates/csharp', version = '0.27.0' }
wit-bindgen-markdown = { path = 'crates/markdown', version = '0.27.0' }
wit-bindgen = { path = 'crates/guest-rust', version = '0.27.0', default-features = false }

wit-bindgen-cpp = { path = 'crates/cpp', version = '0.3.0' }
wit-bindgen-bridge = { path = 'crates/bridge', version = '0.1.0' }

[[bin]]
name = "wit-bindgen"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
wit-bindgen-core = { workspace = true }
wit-bindgen-rust = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-c = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-markdown = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-teavm-java = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-go = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-csharp = { workspace = true, features = ['clap'], optional = true }
wit-component = { workspace = true }
wasm-encoder = { workspace = true }
wit-bindgen-cpp = { workspace = true, features = ['clap'], optional = true }
wit-bindgen-bridge = { workspace = true, features = ['clap'], optional = true }

[features]
default = [
  'c',
  'rust',
  'markdown',
  'teavm-java',
  'go',
  'csharp',
  'cpp',
  'bridge',
]
bridge = ['dep:wit-bindgen-bridge']
c = ['dep:wit-bindgen-c']
cpp = ['dep:wit-bindgen-cpp']
rust = ['dep:wit-bindgen-rust']
markdown = ['dep:wit-bindgen-markdown']
teavm-java = ['dep:wit-bindgen-teavm-java']
go = ['dep:wit-bindgen-go']
csharp = ['dep:wit-bindgen-csharp']
csharp-mono = ['csharp']

[dev-dependencies]
heck = { workspace = true }
wasmtime = { version = "22.0.0", features = ['component-model'] }
wasmtime-wasi =  { version = "22.0.0" }
test-artifacts = { path = 'crates/test-rust-wasm/artifacts' }
wit-parser = { workspace = true }
wasmparser = { workspace = true }
wasm-encoder = { workspace = true }

#[patch.crates-io]
#wit-parser = { git = "https://github.com/bytecodealliance/wasm-tools" }
#wit-component = { git = "https://github.com/bytecodealliance/wasm-tools" }
#wasm-encoder = { git = "https://github.com/bytecodealliance/wasm-tools" }
#wasm-metadata = { git = "https://github.com/bytecodealliance/wasm-tools" }
#wasmparser = { git = "https://github.com/bytecodealliance/wasm-tools" }
#wasmprinter = { git = "https://github.com/bytecodealliance/wasm-tools" }
